Plumbing, domain classes
pivot-libre/tideman pull request #9
Opened 2017-06-30 02:51 UTC by carlschroedl

2017-06-30 02:52 UTC, carlschroedl commented
This isn't ready for merging yet. I'm mostly hoping for a sanity check on the build.xml and composer files at this point.

2017-06-30 02:54 UTC, carlschroedl commented on build.xml
> +
How is this looking so far?
Do you have any pointers on how to grow this?

2017-06-30 02:56 UTC, carlschroedl commented on composer.json
> +        "phing/phing": "2.16.0"
After I added this line for phing, composer complained about being out of sync with the lock file and suggested that I run `composer update`. I did. The diff was big. Is the huge diff for the lock file expected?

2017-06-30 02:58 UTC, carlschroedl commented on src/Ballot.php
> +  	public function __construct(CandidateListList /*...*/$listsOfCandidates) {
I just realized I have php 5.5, so I can't leverage php 5.6+'s varargs syntax yet. I will upgrade soon and uncomment the ellipses.

2017-06-30 15:06 UTC, andrewshell requested changes
Looks fine from what I can tell.  Generally, I stick to the [PSR-2](http://www.php-fig.org/psr/psr-2/) coding standards which use 4 spaces instead of tabs, but that's all I noticed. :-)

Just get your PHP upgraded and restore the varargs and it should be fine to merge.

2017-06-30 22:56 UTC, carlschroedl commented
Thanks @andrewshell ! Will do. I will add a [phing task](https://akrabat.com/checking-your-code-for-psr-2/) to enforce PSR-2.

2017-07-01 12:16 UTC, andrewshell commented
For reference, here is the boilerplate skeleton I typically use for new libraries.  That includes checking for PSR-2: [Cadre.Package](https://github.com/cadrephp/Cadre.Package)

2017-07-01 12:27 UTC, carlschroedl commented
Even better! Thanks!

2017-07-03 19:20 UTC, andrewshell commented
Any reason not to merge this already? Ideally, pull requests are single features/bug fixes.

2017-07-03 19:20 UTC, andrewshell approved these changes

2017-07-03 19:22 UTC, merged

2017-07-03 20:21 UTC, carlschroedl commented
Nope! No reason to wait. I will add a couple more tests in a subsequent PR to get coverage up to 100%. Thanks for reviewing and thanks for merging!

2017-07-03 20:30 UTC, andrewshell commented
Also, it will make PRs and merges easier if you do work in feature branches on your fork instead of in your forks 0.x branch.

2017-07-03 20:38 UTC, carlschroedl commented
Yeah. I goofed. Sorry. Will do next time!